config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :tasks do
    resources :notes, only: [:create], controller: 'tasks/notes'
  end
  resources :categories

  root 'tasks#index'
end

app/models/ability.rb
# frozen_string_literal: true

class Ability
  include CanCan::Ability

  def initialize(user)
    can :manage, Task, owner_id: user.id
    can :read, Task, participant_users: { user_id: user.id }
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
# == Schema Information
#
# Table name: categories
#
#  id          :bigint           not null, primary key
#  name        :string
#  description :text
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#
class Category < ApplicationRecord
  has_many :tasks
  validates :name, presence: true, uniqueness: { case_sensitive: false }
  validates :description, presence: true
end

app/models/note.rb
# == Schema Information
#
# Table name: notes
#
#  id         :bigint           not null, primary key
#  body       :text
#  user_id    :bigint           not null
#  task_id    :bigint           not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#
class Note < ApplicationRecord
  belongs_to :user
  belongs_to :task

  validates :body, presence: true
end

app/models/participant.rb
class Participant < ApplicationRecord
  belongs_to :user
  belongs_to :task
end

app/models/task.rb
# == Schema Information
#
# Table name: tasks
#
#  id          :bigint           not null, primary key
#  name        :string
#  description :text
#  due_date    :date
#  category_id :bigint           not null
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#  owner_id    :bigint           not null
#  code        :string
#
class Task < ApplicationRecord
  belongs_to :category
  belongs_to :owner, class_name: 'User'
  has_many :participant_users, class_name: 'Participant'
  has_many :participants, through: :participant_users, source: :user
  has_many :notes

  validates :participant_users, presence: true
  validates :name, presence: true, uniqueness: { case_sensitive: false }
  validates :description, presence: true
  validate :due_date_validity

  before_create :create_code
  after_create :send_email

  accepts_nested_attributes_for :participant_users, allow_destroy: true

  private

  def due_date_validity
    return if due_date.blank? || due_date > Date.today
    errors.add :due_date, I18n.t('tasks.errors.invalid_due_date')
  end

  def create_code
    self.code = "#{owner.id}#{Time.now.to_i.to_s(36)}#{SecureRandom.hex(8)}"
  end

  def send_email
    (participants + [owner]).each do |user|
      ParticipantMailer.with(user: user, task: self).new_task_email.deliver!
    end
  end
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                     :bigint           not null, primary key
#  email                  :string           default(""), not null
#  encrypted_password     :string           default(""), not null
#  reset_password_token   :string
#  reset_password_sent_at :datetime
#  remember_created_at    :datetime
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  # avoid same name in relations, owned task vs task
  has_many :owned_tasks
  has_many :participations, class_name: 'Participant'
  has_many :tasks, through: :participations
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :set_locale

  before_action :authenticate_user!

  rescue_from CanCan::AccessDenied do |exception|
    redirect_to root_path
  end

  private

  def set_locale
    I18n.locale = 'es'
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: %i[ show edit update destroy ]

  # GET /categories or /categories.json
  def index
    @categories = Category.all
  end

  # GET /categories/1 or /categories/1.json
  def show
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories or /categories.json
  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to category_url(@category), notice: "Category was successfully created." }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1 or /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to category_url(@category), notice: "Category was successfully updated." }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1 or /categories/1.json
  def destroy
    @category.destroy

    respond_to do |format|
      format.html { redirect_to categories_url, notice: "Category was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def category_params
      params.require(:category).permit(:name, :description)
    end
end

app/controllers/tasks/notes_controller.rb
class Tasks::NotesController < ApplicationController
  before_action :set_task

  def create
    @note = @task.notes.new(note_params)
    @note.user = current_user
    @note.save
  end

  private

  def note_params
    params.require(:note).permit(:body)
  end

  def set_task
    @task = Task.find(params[:task_id])
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  load_and_authorize_resource
  before_action :set_task, only: %i[ show edit update destroy ]

  # GET /tasks or /tasks.json
  def index
    @tasks = Task.joins(:participants).where(
      'owner_id = ? OR participants.user_id = ?',
      current_user.id,
      current_user.id
    ).group(:id)
  end

  # GET /tasks/1 or /tasks/1.json
  def show
  end

  # GET /tasks/new
  def new
    @task = Task.new
  end

  # GET /tasks/1/edit
  def edit
  end

  # POST /tasks or /tasks.json
  def create
    @task = Task.new(task_params)
    @task.owner = current_user

    respond_to do |format|
      if @task.save
        format.html { redirect_to task_url(@task), notice: "Task was successfully created." }
        format.json { render :show, status: :created, location: @task }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tasks/1 or /tasks/1.json
  def update
    respond_to do |format|
      if @task.update(task_params)
        format.html { redirect_to task_url(@task), notice: "Task was successfully updated." }
        format.json { render :show, status: :ok, location: @task }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tasks/1 or /tasks/1.json
  def destroy
    @task.destroy

    respond_to do |format|
      format.html { redirect_to tasks_url, notice: "Task was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_task
      @task = Task.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def task_params
      params.require(:task).permit(
        :name,
        :description,
        :due_date,
        :category_id,
        participant_users_attributes: [
          :user_id,
          :role,
          :id,
          :_destroy
        ]
      )
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/categories/_form.html.haml
= simple_form_for(@category) do |f|
	= f.error_notification
	= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present?
	.form-inputs
		.row
			.col-12
				= f.input :name, label: 'Nombre'
		.row
			.col-12
				= f.input :description, as: :text, label: 'Descripción'
	.form-actions
		= f.button :submit, class: 'btn btn-info'

app/views/categories/edit.html.haml
.category.edit-page
  .card
    .card-body
      %h2 Editando categoría
      = render 'form'
      = link_to t('common.show'), @category, class: 'btn-interaction'
      \|
      = link_to t('common.back'), categories_path, class: 'btn-interaction'

app/views/categories/index.html.haml
.categories.index-page
  .card
    .card-body
      %h1 Lista de Categorías
      %table.table
        %thead
          %tr
            %th Nombre
            %th Descripción
            %th
            %th
            %th
        %tbody
          - @categories.each do |category|
            %tr
              %td= category.name
              %td= category.description
              %td= link_to t('common.show'), category
              %td= link_to t('common.edit'), edit_category_path(category)
              %td= link_to t('common.destroy'), category, :method => :delete, :data => { :confirm => t('common.are_you_sure') }
        %br
        .text-right
          = link_to 'Nueva Categoría', new_category_path, class: 'btn btn-info'

app/views/categories/new.html.haml
.category.new-page
  .card
    .card-body
      %h2 New Category
      = render 'form'
      = link_to t('common.back'), categories_path, class: 'btn-interaction'

app/views/categories/show.html.haml
.category.show-page
  .card
    .card-body
      %p
        %b Nombre:
        = @category.name
      %p
        %b Descripción:
        = @category.description
      = link_to t('common.edit'), edit_category_path(@category), class: 'btn-interaction'
      \|
      = link_to t('common.back'), categories_path, class: 'btn-interaction'

app/views/layouts/_messages.html.haml
- flash.each do |name, msg|
  - if msg.is_a?(String)
    %br
    %div{:class => "alert alert-#{name.to_s == 'notice' ? 'success' : 'danger'}"}
      %button.close{"aria-hidden" => "true", "data-dismiss" => "alert", :type => "button"} &times;
      = content_tag :div, msg, :id => "flash_#{name}"

app/views/layouts/_navbar.html.haml
%nav.navbar.navbar-expand-lg.navbar-dark.bg-dark-blue
  %a.navbar-brand
    = image_tag 'logo.png', class: 'd-inline-block align-top', height: 50
  %button.navbar-toggler{"aria-controls" => "navbarNavDropdown", "aria-expanded" => "false", "aria-label" => "Toggle navigation", "data-target" => "#navbarNavDropdown", "data-toggle" => "collapse", :type => "button"}
    %span.navbar-toggler-icon
  #navbarNavDropdown.collapse.navbar-collapse
  %ul.navbar-nav
    %li.nav-item.active
      %a.nav-link{ href: root_path }
        Inicio
        %span.sr-only (current)
    %li.nav-item
      %a.nav-link{ href: categories_path } Categorías
  = link_to 'Crear Tarea', new_task_path, class: 'btn btn-light ml-2'
  .dropdown.dropdown-user
    %a#userMenu{"aria-expanded" => "false", "aria-haspopup" => "true", "data-toggle" => "dropdown"}
      = image_tag "https://robohash.org/#{current_user.email}?size=38x38"
    .dropdown-menu.dropdown-menu-right{"aria-labelledby" => "userMenu"}
      .dropdown-item.small.text-right= current_user.email
      .dropdown-divider
      = link_to destroy_user_session_path, method: :delete, class: 'dropdown-item' do
        .fas.fa-sign-out
        Cerrar sesión

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Organizer</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= link_to 'cerrar sesion', destroy_user_session_path, method: :delete %>
    <%= yield %>
  </body>
</html>

app/views/layouts/application.html.haml
-# frozen_string_literal: true
-# app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}
    %title Organizador
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    = render 'layouts/navbar'
    .container.mt-4.pb-4
      .main-flash-messages
        = render 'layouts/messages'
      = yield

app/views/layouts/devise.html.haml
!!!
%html
	%head
		%meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
		%title Tasker
		= csrf_meta_tags
		= csp_meta_tag
		= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'
		= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
	%body
		.container
			.main-flash-messages
				= render 'layouts/messages'
		.fullscreen
			.container
				= yield

app/views/layouts/xapplication.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Organizer</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= link_to 'cerrar sesion', destroy_user_session_path, method: :delete %>
    <%= yield %>
  </body>
</html>

app/views/tasks/_form.html.erb
<%= simple_form_for(@task) do |form| %>
  <%= form.error_notification %>
  <%= form.error_notification message: form.object.errors[:base].to_sentence if form.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= form.input :name, label: t('.name') %>
    <%= form.input :description, label: t('.description') %>
    <%= form.input :due_date, label: t('.due_time') %>
    <%= form.association :category, label: t('categories.category') %>
  </div>

  <%= link_to_add_nested(form, :participant_users, '#participants', partial: 'participant_users_fields', link_text: "Agregar Participante") %>
  <div id="participants">
    <%= form.fields_for :participant_users do |g|%>
      <%= render 'participant_users_fields', form: g %>
    <% end %>
  </div>

  <div class="form-actions">
    <%= form.button :submit %>
  </div>
<% end %>

app/views/tasks/_participant_users_fields.html.erb
<div class="nested-fields">
  <%= form.input :user_id, as: :select, collection: User.all - [current_user] %>
  <%= form.input :role %>
  <%= link_to_remove_nested(form) %>
</div>

app/views/tasks/edit.html.haml
%h1 Editing task

= render 'form'

= link_to 'Show', @task
\|
= link_to 'Back', tasks_path

app/views/tasks/index.html.haml
%h1 Listing tasks

%table
  %thead
    %tr
      %th Name
      %th Description
      %th Due date
      %th Category
      %th
      %th
      %th

  %tbody
    - @tasks.each do |task|
      %tr
        %td= task.name
        %td= task.description
        %td= task.due_date
        %td= task.category
        %td= link_to 'Show', task
        %td= link_to 'Edit', edit_task_path(task)
        %td= link_to 'Destroy', task, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Task', new_task_path

app/views/tasks/new.html.haml
%h1 New task

= render 'form'

= link_to 'Back', tasks_path

app/views/tasks/notes/_note.html.haml
%p= note.body
%p= time_ago_in_words note.created_at
%p= note.user.email
%hr

app/views/tasks/notes/create.js.erb
<%- if @note.persisted? %>
    var parentNode = document.querySelector(".notes-container .notes")
    var div = document.createElement("div")
    div.innerHTML = "<%= j render 'tasks/notes/note', note: @note %>"
    parentNode.appendChild(div)
    document.getElementById("note_body").value = "";
    window.scrollTo({
        top: window.innerHeight,
        behavior: "smooth"
    });
<% end %>

app/views/tasks/show.html.haml
%p#notice= notice

%p
  %b Name:
  = @task.name
%p
  %b Description:
  = @task.description
%p
  %b Due date:
  = @task.due_date
%p
  %b Category:
  = @task.category

.notes-container
  .notes
    - @task.notes.each do |n|
      = render 'tasks/notes/note.html.haml', note: n
  = simple_form_for Note.new, url: task_notes_path(task_id: @task.id), remote: true do |f|
    = f.input :body, label: false, as: :string, placeholder: 'Enter your note', input_html: { autocomplete: :off }

= link_to 'Edit', edit_task_path(@task)
\|
= link_to 'Back', tasks_path